### RECUPERAR TODAS LOS LIBROS
GET http://localhost:1234/api/libros


### RECUPERAR LIBRO POR ID
GET http://localhost:1234/api/libros/65d4d8987121c5a52af77cb5


### CREAR LIBRO CON POST
POST http://localhost:1234/api/libros
Content-Type: application/json

{
  "id_categoria": "507f1f77bcf86cd799439011",
  "titulo": "Pride and Prejudice 43",
  "autor": "Jane Auste1",
  "isbn": "7978014625491",
  "disponibilidad": true,
  "cantidad": 2,
  "imageLink": "/images/le-pere-goriot.jpg"
}


### ACTUALIZAR LIBRO CON PATCH

PATCH http://localhost:1234/api/libros/65d4d69287392a6da58c232f
Content-Type: application/json

{

  "autor": "Jaane ROmdom",
  "isbn": "7978014625491",
  "disponibilidad": false,
  "cantidad": 2,
  "imageLink": "/images/le-pere-goriot.jpg"
}

### ELIMINAR LIBRO CON DELETE
DELETE http://localhost:1234/api/libros/65d4d69287392a6da58c232f





